name: CI Pipeline

# Trigger the workflow on:
# 1. Pushes to any branch (know if it breaks before you even open a PR)
# 2. Pull Requests targeting main
on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    # 3. Install dependencies
    - name: Install dependencies with uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync

    # 4. Run Tests
    - name: Run Tests
      # 'uv run' ensures it uses the virtual environment created by 'uv sync'
      run: uv run pytest


  build-and-run:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: .
          tags: bda-svc:latest
          load: true # Makes image available to docker run

      - name: Run containerized test
        run: docker run --rm bda-svc:latest -h